### PR TITLE
added secrets.js and installed pg and created a db.js file

### PR DESCRIPTION
**Pull request by therosstar**

### CODE REVIEW

**Review by tommypurcell — CHANGES_REQUESTED** [review]
We should check with your team and agree on using index.js or app.js

**Comment by therosstar** [comment]
this is ready

**Review by tommypurcell — CHANGES_REQUESTED** [review]
users/1 doesnt work

**Review by tommypurcell — COMMENTED** [review]
We already have a secrets.js, db.js, and pg on main. please pull main and make a new branch to do the user routes and houses routes. im closing this pull request

**Pull request closed without merging**
